#!/bin/sh

uci -q show system.@watchcat[0] || {
	uci add system watchcat
	uci set system.@watchcat[0].period=6h
	uci set system.@watchcat[0].pingperiod=30m
	uci set system.@watchcat[0].mode=network
	uci set system.@watchcat[0].pingsize=standard
	uci set system.@watchcat[0].pinghosts="8.8.8.8"
	uci set system.@watchcat[0].forcedelay=60
	uci commit
}
